services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: c-producto-app-prueba
    ports:
      - "5000:3000"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DOCKER_ENV=true 
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres_net

  postgres:
    image: postgres:15
    container_name: c-postgres-container
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_dt:/var/lib/postgresql/data
    networks:
      - postgres_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  postgres_dt:

networks:
  postgres_net:
